name: Remove Stale Workflow Runs
description: Removes workflow runs of delete p
inputs:
  token:
    description: Personal access token (auto-populated). It is used only because anonymous requests are rate-limited. It can be overridden to an empty value.
    required: true
    default: ${{ github.token }}
  repository:
    description: Repository name with owner. E.g. actions/checkout
    required: true
    default: ${{ github.repository }}
  dry_run:
    description: Only find stale workflow runs but do not delete anything
    default: 'false'
  max_runs_limit:
    description: Limits the number of fetched workflow runs, e.g. 500. Defaults to 0, meaning no limit set.
    default: '0'
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
