name: Remove Stale Workflow Runs
description: Removes workflow runs of delete p
inputs:
  token:
    description: Personal access token (auto-populated). It is used only because anonymous requests are rate-limited. It can be overridden to an empty value.
    default: ${{ github.token }}
  repository:
    description: Repository name with owner. E.g. actions/checkout
    required: true
outputs: {}
runs:
  using: "node16"
  main: "dist/index.js"
